name: Release pipeline
on:
  push:
    branches: [main]
  pull_request_target:

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying..."
