name: Dispatch TOCTOU
on:
  workflow_dispatch:
    inputs:
      pr:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr }}/head
      - run: make build
